# Generated by Django 5.1.3 on 2024-12-02 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_image_user_liked_user_recommemded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='recommemded',
            new_name='recommended',
        ),
    ]
